name: Publish Packages

on:
  push:
    branches:
      - master

concurrency: : ${{ github.workflow }}-${{ github.ref }}

jobs:
  Release:
    name: Build & Publish @latest Release
    if: github.repository == 'tutkli/ngx-mode-watcher'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version

      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore(release): version package"
          title: "chore(release): version package"
          publish: npm run ci:publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
